Populate dynamic api examples
micro-nova/AmpliPi pull request #114
Opened 2021-05-03 21:33 UTC by linknum23

Make Amplipi generate API examples based on its current configuration to make it simpler to change things with the API.

2021-05-03 21:35 UTC, linknum23 commented
Can you guys check this out and make sure it populates the examples you expect?

Note: Firefox still likes to cache the amplipi_api.yaml file

2021-05-04 14:17 UTC, Lohrer requested changes
docs/amplipi_api.yaml needs to be added to the .gitignore

2021-05-05 17:26 UTC, micronova-jb approved these changes

2021-05-05 19:01 UTC, linknum23 commented
@Lohrer I ended up not being able to ignore that yaml file since it is needed by the github hosted website.

2021-05-05 19:03 UTC, merged