Add multiple zone selection
micro-nova/AmpliPi pull request #228
Opened 2021-12-10 21:50 UTC by klay2000

PR to make zone selector a multiselector.

2021-12-10 22:03 UTC, linknum23 requested changes

2021-12-10 22:03 UTC, linknum23 commented on web/templates/index.html.j2
> +  <!-- UUID CDN -->
remove UUID and qs, below and keep these lines

2021-12-10 22:13 UTC, linknum23 requested changes

2021-12-10 22:13 UTC, linknum23 commented on web/templates/index.html.j2
> +                <optgroup label="Groups">
Can you hide the group and zone labels if there aren't any?

2021-12-17 15:39 UTC, linknum23 commented on web/templates/index.html.j2
> +  <!-- UUID CDN -->
lines 349-358 should be removed, can't suggest that with GH

2021-12-17 18:51 UTC, Lohrer commented
Just checked this out. It's a bit awkward since the action that actually performs the zone update is "close the zone dropdown" AKA click anywhere that's not the zone selection dropdown. Some kind of "Add" or "OK" button would be nice, but it does technically work as-is.

It also doesn't seem to work on the Android app at all, but I like that there's an OK button there so it makes more intuitive sense.

2021-12-21 21:10 UTC, linknum23 commented
> It also doesn't seem to work on the Android app at all, but I like that there's an OK button there so it makes more intuitive sense.

Just tested this in the app and it works as expected.

2021-12-21 21:12 UTC, linknum23 approved these changes

2021-12-21 21:32 UTC, Lohrer commented
> We can think about adding a button in the future, both Klayton and I were having trouble getting a button to look good CSS-wise.
> Just tested this in the app and it works as expected.

Yeah after testing again I don't get the button that I saw before and things work as expected. I must have tested too soon or maybe grabbed an old commit somehow, I'm not sure.

2021-12-21 21:52 UTC, merged