Streamer Software
micro-nova/AmpliPi pull request #460
Opened 2023-03-31 16:00 UTC by klay2000

Changes for supporting streamer box, eeprom(s), and eink display.

2023-04-24 21:02 UTC, linknum23 requested changes
you will need to add support for the streamer config in app.load_factory_config right now it defaults to a config with 6 zones. 

Michael will review the changes to the display code.

2023-04-26 21:01 UTC, Lohrer requested changes
First off, rebase on develop.

Things to fix that I've noticed so far:
* RCA inputs shouldn't be available.
* Factory reset config adds zones.
* Updates fail due to not being able to program the preamp firmware.

Minor issue that can be ignored or fixed later:
* Zones still show up in the API documentation page.
* The example preset "Mute Some" returns "TypeError: response.presets is undefined"
* Mute all still occasionaly gets added (not sure by what) as a preset (which fails to run properly).
* The RCA audiodetector will be installed (note, there's currently a bug where a deploy won't install the audiodetector but the updater will)
* Shortcuts to tests that won't work are still placed on the Desktop.
* `Error: no preamps found`. AmpliPi still tries to connect to the non-existent preamp. I think enough checks are in place that no attempted I2C messages are sent but we should probably be using the "Mock" preamp.

Open questions:
* Keep amplipi hostname?
* I get bluetooth errors at startup even though no bluetooth streams are configured. It's possible this is fixed by rebasing on develop which has bluetooth updates.
```
/usr/bin/bluetoothctl
Error checking for bluetooth hardware: Command '['bluetoothctl', 'show']' timed out after 0.5 seconds
bluetooth dongle unavailable
```

2023-05-03 16:55 UTC, linknum23 commented
@klay2000 Can you look at the changes I made to the display and verify that they make sense?

2023-05-03 18:04 UTC, jonahshader reviewed
No major concerns, looks good

2023-05-03 21:04 UTC, linknum23 approved these changes

2023-05-03 21:04 UTC, merged