Add text wrapping to stream names, update CHANGELOG
micro-nova/AmpliPi pull request #710
Opened 2024-05-07 14:18 UTC by SteveMicroNova

### What does this change intend to accomplish?
Long stream names used to overflow off of the player card and would take the close stream button with it, stream names will now wrap to avoid that issue
 
### Checklist

* [ ] Have you tested your changes and ensured they work?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] If applicable, have you updated the documentation/manual?
* [ ] If applicable, have you updated the CHANGELOG?
* [ ] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`
* [ ] Have you written new tests for your core features/changes, as applicable?
* [ ] If this is a UI change, have you tested it across multiple mobile and web platforms?

2024-05-07 14:19 UTC, SteveMicroNova commented
Before:
![image](https://github.com/micro-nova/AmpliPi/assets/114415937/547f5409-691f-4203-a50b-1e78bb8d1fc3)

After:
![image](https://github.com/micro-nova/AmpliPi/assets/114415937/49a59225-8208-4cec-8761-5d9fc602ab3f)

2024-05-07 17:33 UTC, rtertiaer reviewed
not a fan of this look. perhaps a marquee is a decent solution here?

2024-05-07 19:24 UTC, SteveMicroNova commented
New variant on this:

Wide:
![image](https://github.com/micro-nova/AmpliPi/assets/114415937/5fbb8f35-4fe3-4d6d-ae4b-ac77647163f4)

Thin:
![image](https://github.com/micro-nova/AmpliPi/assets/114415937/1220f1ab-7385-4acc-891c-fe610b39a1ba)

2024-05-13 15:50 UTC, rtertiaer requested changes

2024-05-13 15:50 UTC, rtertiaer commented on web/src/components/StreamBadge/StreamBadge.scss
> +  color: general.$text-color;
pls revert and squash this `color` line change if you're gonna keep this line; it's  bad form to screw up `git blame` like this

2024-05-15 12:57 UTC, rtertiaer approved these changes
:clap:

2024-05-15 12:58 UTC, merged