Refresh button
micro-nova/AmpliPi pull request #734
Opened 2024-05-29 15:49 UTC by mjustian

### What does this change intend to accomplish?
There was no easy way to reset a broken stream before. This adds a button to the player view and the modal in settings to do that. The buttons interface with a stream command on the REST API that resets a stream. IT supports both BaseStream and PersistentStream.

### Checklist

* [X ] Have you tested your changes and ensured they work?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] If applicable, have you updated the documentation/manual?
* [X] If applicable, have you updated the CHANGELOG?
*  X] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`
* [X] If this is a UI change, have you tested it across multiple browser platforms?
* [X] If this is a UI change, have you tested across multiple viewport sizes (ie. desktop versus mobile)?

2024-05-29 18:36 UTC, rtertiaer requested changes
if you absolutely must wholesale run files thru a linter, can you at least put those in separate commits so I can easily review what's functionally changed? (not a huge fan of that anyhow, unless you're substantially rewriting a file anyhow.)

2024-05-31 16:42 UTC, linknum23 commented
Opinions below. I'll let others chime in with their thoughts and see if we can reach a consensus.

- I really like being able to reset the stream from the stream modal since it takes a couple of clicks to get there and has an explanation as to what it does and why.
- My instinct is that the actual reset button on the player is too easy and takes up too much space for an operation that shouldn't be needed under most scenarios.
- After talking with Michael on this I like the word restart for this instead of reset. I think it is a less ambiguous name and clearly explains what it does in one work.

2024-05-31 19:04 UTC, gorski123 commented
The restart button should be shown by the currently playing stream. I dont think we need to write out reset or restart, rather just a button with a logo (reset logo or the current recycle logo you are using) should suffice. I was thinking something like this:
![image](https://github.com/micro-nova/AmpliPi/assets/20228663/d546c935-e750-4bca-9096-879a5ae12aba)
![image](https://github.com/micro-nova/AmpliPi/assets/20228663/79c62325-2e9a-4c13-8a63-66dfdb384a81)

2024-05-31 19:16 UTC, linknum23 commented
I don't think the main view with all of the streams needs a reset button.
It doesn't even have the much more used play/pause/next song button.

On Fri, May 31, 2024 at 3:05 PM Jason Gorski ***@***.***>
wrote:

> The restart button should be shown by the currently playing stream. I dont
> think we need to write out reset or restart, rather just a button with a
> logo (reset logo or the current recycle logo you are using) should suffice.
> I was thinking something like this:
> image.png (view on web)
> <https://github.com/micro-nova/AmpliPi/assets/20228663/d546c935-e750-4bca-9096-879a5ae12aba>
> image.png (view on web)
> <https://github.com/micro-nova/AmpliPi/assets/20228663/79c62325-2e9a-4c13-8a63-66dfdb384a81>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/micro-nova/AmpliPi/pull/734#issuecomment-2142832272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEZPO33TNL44BWTYLTY553ZFDCWJAVCNFSM6AAAAABIPHGWZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBSHAZTEMRXGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-05-31 19:27 UTC, mjustian commented
If the main view had a button like that, it would be really hard to tap on a mobile device.

2024-05-31 19:29 UTC, mjustian commented
Also, would the end user know the recycle symbol would mean "restart stream"? Next to the icon it isn't really clear that it's a button.

2024-05-31 19:32 UTC, gorski123 commented
Hows about just putting it next to all the other buttons (play pause etc)? Thats prolly where it belongs...

2024-05-31 20:51 UTC, mjustian commented
That would make sense, but on views such as Pandora which has 5 buttons already, it would be a bit long, especially on a mobile device. I'm not 100% sure if that would be worth making the rest of the buttons much smaller to fit the reset button.

2024-05-31 20:54 UTC, gorski123 commented
Can the buttons wrap to a second line if they dont fit? The pandora buttons already go off the screen in mobile, perhaps implementing some code to wrap to a second line could squash that bug as well.

2024-05-31 21:17 UTC, mjustian commented
I think it would look odd if the thumbs up and thumbs down buttons are on different levels. Also, putting it with the rest of the controls conflicts with the "having a restart button so easily accessible means it will break often" opinion. It might be better to make the controls smaller on mobile, rather than wrapping to a second line.

2024-06-04 19:11 UTC, rtertiaer approved these changes
one last request, but otherwise you have my approval. could you detail in a comment in the code why you need a `src = self.src` in `BaseStream`'s `restart()`, but not in `PersistentStream`?

2024-06-04 19:11 UTC, rtertiaer commented
oh, and rebasing + squashing this is very preferred too.

2024-06-04 20:41 UTC, mjustian commented
Reason for src = self.src in BaseStream:
the _disconnect function sets self.src to None, but it is also needed to run the connect function. The PersistentStream does not have any arguments when activating, so it's not needed.

2024-06-04 21:47 UTC, merged