Kick disabled zones and hide disabled groups
micro-nova/AmpliPi pull request #740
Opened 2024-06-04 17:07 UTC by mjustian

### What does this change intend to accomplish?
Kicks zones that have been disabled off of their sources since right now they get stuck with no way to add or remove them from their source. Also hides groups where all zones have been disabled, and treats the remaining zones of a group as if they were the only ones if only a few of the zones were disabled.

### Checklist

* [X] Have you tested your changes and ensured they work?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] If applicable, have you updated the CHANGELOG?
* [ ] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`
* [ ] Have you written new tests for your core features/changes, as applicable?

2024-06-04 19:13 UTC, rtertiaer commented on web/src/utils/GroupZoneFiltering.jsx
> +        } else if (fitness == bestFitness) {
:muscle:

2024-06-19 14:41 UTC, rtertiaer requested changes

2024-06-20 19:54 UTC, mjustian commented on CHANGELOG.md
> +  * Groups containing only disabled zones no longer selectable
Moved!

2024-06-20 19:58 UTC, rtertiaer approved these changes

2024-06-20 20:13 UTC, merged