External Media Stopper
micro-nova/AmpliPi pull request #913
Opened 2024-08-26 21:00 UTC by SteveMicroNova

### What does this change intend to accomplish?
Make media_device stream use vsrc instead of src, properly end processes
Closes #912 

### Checklist

* [x] Have you tested your changes and ensured they work?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] If applicable, have you updated the CHANGELOG?
* [x] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`

2024-08-26 21:07 UTC, SteveMicroNova commented
I feel that small changes like this do not warrant a changelog update, let me know if this is not the case

2024-08-26 21:13 UTC, klay2000 requested changes

2024-08-26 21:13 UTC, klay2000 commented on amplipi/streams/media_device.py
> +      if self.song_index < len(self.song_list) and utils.virtual_output_device(vsrc) is not None:
I think you can get rid of ``and utils.virtual_output_device(vsrc) is not None``

2024-08-26 21:13 UTC, klay2000 commented on amplipi/streams/media_device.py
> +      if self.song_index < len(self.song_list) and utils.virtual_output_device(vsrc) is not None:
try it and lmk

2024-08-27 16:09 UTC, klay2000 approved these changes

2024-08-27 16:10 UTC, merged