LMSConfigPolish
micro-nova/AmpliPi pull request #974
Opened 2024-10-14 14:30 UTC by SteveMicroNova

### What does this change intend to accomplish?
![image](https://github.com/user-attachments/assets/6a2b3f85-6092-457c-bdbf-4a33c8cb0e69)
Change LMS toggle switch so that it doesn't download system config on LMS deactivation, include link to LMS server when LMS Mode is active

### Checklist

* [ ] Have you tested your changes and ensured they work?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`
* [ ] If this is a UI change, have you tested it across multiple browser platforms on both desktop and mobile?

2024-10-14 17:21 UTC, rtertiaer commented on web/src/pages/Settings/Config/ConfigPanels/LMSMode.jsx
>                      open={modalOpen}
not a fan of this change: https://github.com/micro-nova/AmpliPi/issues/976#issuecomment-2411833840 & https://github.com/micro-nova/AmpliPi/pull/805

2024-10-23 15:53 UTC, rtertiaer requested changes
is there any way that button could look a little less haphazardly placed? I don't have any suggestions here - I know we're largely not designers - but I'd love to ensure we at least don't make things look worse. some things that I notice:
* it's a button, but doesn't do a button-like thing - it does a link-like thing
* there are two other types of buttons on the page; this is themed like neither of them
* there's zero margin/padding on this button between it and the divider - feels cramped
* it's not horizontally aligned to anything but the prior content, which feels unfinished

2024-10-23 17:08 UTC, SteveMicroNova commented
> * it's a button, but doesn't do a button-like thing - it does a link-like thing

I'm happy to make it a link again, though we'll probably have to hash that out a little further given Klayton's dislike of my previous link strategy

> * there are two other types of buttons on the page; this is themed like neither of them

Fixed

> * there's zero margin/padding on this button between it and the divider - feels cramped

This is the case for all of the buttons, but obviated by the `contained` styling; corrected in recent commit

> * it's not horizontally aligned to anything but the prior content, which feels unfinished

I've got no good way of fixing this as there isn't really a gridmodel in place for multi-input sections but I've taken a note from the "Upload Config" section and just made there be some spacing between the inputs


![image](https://github.com/user-attachments/assets/da821010-b07c-465a-89c8-716c1e4a59a9)

2025-01-06 16:30 UTC, klay2000 approved these changes
Lincoln, Steve, and I have decided the button-link thing should be fine as long as it opens in a new tab.

2025-01-06 19:41 UTC, merged