Format Admin Settings
micro-nova/AmpliPi pull request #999
Opened 2024-11-19 19:29 UTC by SteveMicroNova

### What does this change intend to accomplish?
Indents subsections to make it more obvious that they are part of a given subheader, add info icons to subheaders to make it clearer that they have info on hoverover

Closes #998 

Before:
![image](https://github.com/user-attachments/assets/682316c8-6c05-47c6-bf13-12b71790ee6a)

After:
![image](https://github.com/user-attachments/assets/68792a47-b906-424a-9dab-77d5bf70316b)

### Checklist

* [x] Have you tested your changes and ensured they work?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`
* [x] If this is a UI change, have you tested it across multiple browser platforms on both desktop and mobile?

2024-11-20 16:38 UTC, rtertiaer requested changes
while you're at it, can you align the textbox elements so they don't look haphazard?

2024-11-20 16:41 UTC, rtertiaer commented
imo, tooltips like this are not good design. they are less [accessible](https://en.wikipedia.org/wiki/Web_accessibility) than the alternative of just describing the feature below its heading, and still aren't actually obvious, even with your svg.

2024-12-06 20:49 UTC, SteveMicroNova commented
Marking this as "Not quite ready yet" due to this funny bug

https://github.com/user-attachments/assets/c4cc5224-6b1d-4ec9-a7ad-f5118511fcc4

2024-12-09 20:06 UTC, SteveMicroNova commented
Problems solved, ready for review

2025-01-06 15:55 UTC, klay2000 requested changes
Overall I think this looks better and the changes are fine at a glance code wise, I would just like the field descriptions to be a little more precise. I'll look at the code more closely once these are updated.

2025-01-06 15:55 UTC, klay2000 commented on amplipi/updater/static/index.html
> +                    Set Password allows you set to a web interface password, which will make it so that you must input the same password to access the app
I think that the password field deserves a better description, I prefer the old one to the new one, however I know it's pretty long, try to condense it a bit.

2025-01-06 15:55 UTC, klay2000 commented on amplipi/updater/static/index.html
> +                  </div>
nitpick: change can to may

2025-01-06 19:32 UTC, klay2000 approved these changes

2025-01-06 19:50 UTC, merged